# based on http://conda.pydata.org/docs/travis.html
language: python
sudo: false

python:
  - "3.4"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy scipy scikit-learn cython joblib pytest
  - pip install -U iterpipes3 python-magic
  - source activate test-environment
  - python setup.py install

script:
  - py.test discoutils/tests

notifications:
  email: false