# based on https://github.com/larsmans/seqlearn/blob/b85c56e3b785745683ea2a6d0907d89405a6b975/.travis.yml
sudo: false
language: python
python:
  - "3.4"

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - python3-numpy
      - python3-scipy

virtualenv:
  system_site_packages: true

install:
  - deactivate
  - virtualenv --system-site-packages testenv
  - source testenv/bin/activate
  - pip install -U pytest Cython iterpipes3 scikit-learn joblib python-magic

script:
  - py.test discoutils/tests
