# based on https://github.com/larsmans/seqlearn/blob/b85c56e3b785745683ea2a6d0907d89405a6b975/.travis.yml

sudo: false

language: python
python: # https://github.com/travis-ci/travis-ci/issues/2219#issuecomment-41804942
  - "3.2"

git:
  depth: 250

addons:
  apt:
    packages:
      - python3-numpy
      - python3-scipy
      - python3-sklearn

virtualenv:
  system_site_packages: true

install:
  - deactivate		
  - virtualenv --system-site-packages testenv		
  - source testenv/bin/activate
  - pip install -U pytest Cython iterpipes3 joblib python-magic --user
  - python setup.py install

script:
  - py.test discoutils/tests
