# based on https://github.com/larsmans/seqlearn/blob/b85c56e3b785745683ea2a6d0907d89405a6b975/.travis.yml

sudo: required
dist: trusty #http://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/

language: python
python: # https://github.com/travis-ci/travis-ci/issues/2219#issuecomment-41804942
  - "3.2_with_system_site_packages"

git:
  depth: 250

addons:
  apt:
    packages:
      - python3-numpy
      - python3-scipy

virtualenv:
  system_site_packages: true

install:
  - pip install -U pytest Cython iterpipes3 scikit-learn joblib python-magic
  - python setup.py install

script:
  - py.test discoutils/tests
